# Generated by Django 5.0.1 on 2024-02-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('listing_app', '0003_alter_joboffer_listing_alter_project_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing_app.listing')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.profile')),
            ],
        ),
    ]
