# Generated by Django 5.0.1 on 2024-02-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0003_alter_application_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['JobOfferDetails', 'ProjectDetails']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
