# Generated by Django 5.0.1 on 2024-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0005_jobofferdetails_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
