# Generated by Django 5.0.1 on 2024-03-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0006_application_is_checked'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOfferDetails',
            new_name='JobOfferApplicationDetails',
        ),
        migrations.RenameModel(
            old_name='ProjectDetails',
            new_name='ProjectApplicationDetails',
        ),
        migrations.AlterField(
            model_name='application',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['JobOfferApplicationDetails', 'ProjectApplicationDetails']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
