# Generated by Django 5.0.1 on 2024-03-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0007_rename_jobofferdetails_jobofferapplicationdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('adjudicate_application', 'Can accept or reject application and view its details')]},
        ),
    ]
