# Generated by Django 5.0.1 on 2024-03-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0008_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferapplicationdetails',
            name='cv',
            field=models.FileField(upload_to='files/'),
        ),
    ]
