# Generated by Django 5.0.1 on 2024-04-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0009_alter_jobofferapplicationdetails_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
    ]
