# Generated by Django 5.0.1 on 2024-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_initial'),
        ('application_app', '0001_initial'),
        ('listing_app', '0003_alter_joboffer_listing_alter_project_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applications',
            field=models.ManyToManyField(through='application_app.Application', to='listing_app.listing'),
        ),
    ]
