# Generated by Django 5.0.1 on 2024-02-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
