# Generated by Django 5.0.1 on 2024-01-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_app', '0001_initial'),
        ('company_profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(through='company_profiles_app.Employment', to='company_profiles_app.company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
