# Generated by Django 5.0.1 on 2024-01-12 20:51

import company_profiles_app.models.company
import authentication_app.models.profile
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=192)),
                ('secondary_address', models.CharField(max_length=192)),
                ('company_logo', models.ImageField(default='images/default/default_company_img.jpg', upload_to=company_profiles_app.models.company.Company.save_company_logo)),
                ('name', models.CharField(max_length=160)),
                ('website', models.URLField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default/default_img.jpg', upload_to=authentication_app.models.profile.Profile.user_directory_path),
        ),
        migrations.CreateModel(
            name='CompanyEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=96)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='authentication_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=96)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='authentication_app.company')),
            ],
        ),
    ]
