# Generated by Django 5.0.1 on 2024-01-12 20:52

import authentication_app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_company_alter_profile_image_companyemails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default/default_profile_img.jpg', upload_to=authentication_app.models.profile.Profile.user_directory_path),
        ),
    ]
