# Generated by Django 5.0.1 on 2024-01-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(to='authentication_app.company'),
        ),
    ]
