# Generated by Django 5.0.1 on 2024-01-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_profile_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyemails',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companyphones',
            old_name='company_id',
            new_name='company',
        ),
    ]
