# Generated by Django 5.0.1 on 2024-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='key_responsibilities',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='preferred_qualifications',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='remote_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='required_qualifications',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_range_max',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_range_min',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='work_commitment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('zero_hours', 'Zero-Hours'), ('flextime', 'Flextime')], max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('in_office', 'In-office')], max_length=25),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='benefits',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
