# Generated by Django 5.0.1 on 2024-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0002_remove_joboffer_salary_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('suggestion', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
