# Generated by Django 5.0.1 on 2024-02-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0002_rename_jobofferproxy_joboffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='listing_app.listing'),
        ),
        migrations.AlterField(
            model_name='project',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='listing_app.listing'),
        ),
        migrations.DeleteModel(
            name='UserSuggestion',
        ),
    ]
