# Generated by Django 5.0.1 on 2024-02-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0003_usersuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='user_suggestions',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='listing_app.usersuggestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='work_commitment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('zero_hours', 'Zero-Hours'), ('flextime', 'Flextime'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('in_office', 'In-office'), ('other', 'Other')], max_length=25),
        ),
    ]
