# Generated by Django 5.0.1 on 2024-03-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_alter_customuser_managers'),
        ('company_profiles_app', '0007_rename_person_employment_profile'),
        ('listing_app', '0008_alter_listing_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='company_profiles_app.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.profile'),
            preserve_default=False,
        ),
    ]
