# Generated by Django 5.0.1 on 2024-03-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0009_joboffer_company_project_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='industries',
            field=models.ManyToManyField(to='listing_app.industry'),
        ),
    ]
