# Generated by Django 5.0.1 on 2024-03-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0010_industry_listing_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
    ]
