# Generated by Django 5.0.1 on 2024-03-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0011_remove_listing_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='work_commitment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('zero_hours', 'Zero-Hours'), ('flextime', 'Flextime')], max_length=50),
        ),
    ]
