# Generated by Django 5.0.1 on 2024-02-13 09:05

import company_profiles_app.models.company
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=192)),
                ('secondary_address', models.CharField(max_length=192)),
                ('company_logo', models.ImageField(default='images/default/default_company_img.jpg')),
                ('name', models.CharField(max_length=160)),
                ('website', models.URLField(max_length=128)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('verify_company', 'Can verify the company if it is legit')],
            },
        ),
        migrations.CreateModel(
            name='CompanyEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=96)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='company_profiles_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=96)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='company_profiles_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('owner', 'Owner'), ('human_resources', 'Human Resources'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('employee', 'Employee'), ('intern', 'Intern'), ('other', 'Other')], max_length=15)),
                ('is_associate', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profiles_app.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.profile')),
            ],
            options={
                'permissions': [('verify_associate', 'Can verify if a person is associated with the given company')],
            },
        ),
    ]
