# Generated by Django 5.0.1 on 2024-02-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=96)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyphones',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='identifiers',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='company_profiles_app.companyidentifiers'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyEmails',
        ),
        migrations.DeleteModel(
            name='CompanyPhones',
        ),
    ]
