# Generated by Django 5.0.1 on 2024-02-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0002_companyidentifiers_remove_companyphones_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='identifiers',
        ),
        migrations.DeleteModel(
            name='CompanyIdentifiers',
        ),
    ]
