# Generated by Django 5.0.1 on 2024-02-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0003_remove_company_identifiers_delete_companyidentifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=96)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profiles_app.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
