# Generated by Django 5.0.1 on 2024-02-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0004_companyidentifiers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyIdentifiers',
        ),
    ]
