# Generated by Django 5.0.1 on 2024-03-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0008_employment_is_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employment',
            options={'permissions': [('verify_associate', 'Can verify if a person is associated with the given company'), ('give_rights', 'Can delegate permissions to other associates to manage company resources and data.')]},
        ),
    ]
