# Generated by Django 5.0.1 on 2024-03-31 00:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0009_alter_employment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='company_logo'),
        ),
    ]
