# Generated by Django 5.0.1 on 2024-04-21 08:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profiles_app', '0011_alter_company_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='company_logo'),
        ),
    ]
